### ISSUE TITLE
Is this supposed to be a button?

### ISSUE THREAD

**Issue by johnsiwicki** [bs-production/sure-dry-template#17]
Is this supposed to be a button?
![image](https://user-images.githubusercontent.com/36214317/134663354-58c47460-9c93-4a45-a2ff-953d8aa643a6.png)

_Originally posted by @IamStephan in https://github.com/bs-production/sure-dry-template/issues/14#issuecomment-926534030_

**Comment by johnsiwicki** [comment]
It should link to this page https://www.suredrybasements.com/about-us/financing.html

**Comment by IamStephan** [comment]
Wrapper the entire banner in an anchor tag and linked it to the page
