### ISSUE TITLE
Viewport overflow issues

### ISSUE THREAD

**Issue by IamStephan** [bs-production/sure-dry-template#19]
The following pages have either module or widgets that are overflowing that page on mobile: (related to #15)

- https://www.suredrybasements.com/about-us/photo-gallery/24234-album-crawlspace-waterproofing-in-baileys-harbor-wi.html#ad-image-4
- https://www.suredrybasements.com/free-estimate/confirmation.html?test=style

The reason this is happening is that those modules and widgets expect the markup (and parent styles) to be the same as the old template. There are two essential classes from foundation CSS that are missing in parent DOM elements; `row` and `columns`.

There are 3 solutions:
1. The new template already includes the legacy grid style from Foundation. So just adding those classes to the appropriate parent elements would fix the majority of the overflow issues (There is one style that needs to be added to the widget/module that isn't included in my legacy grid port: the `overflow: hidden` class from Foundation)
2. A more non-destructive approach might be to wrap the module or widget inside divs that mimics the old template structure inside the content editor (The TinyMCE code editor).
3. The last solution would be to create a new widget/module template specific to sure dry and using that.

**Comment by IamStephan** [comment]
Going with the first solution would require more work than it would solve the actual issue since it would most likely introduce unexpected bugs that would be hard to find and fix.

The second solution is probably the best of the three since it is low-effort and would only affect the pages that include the module or widget. Even on module pages, it shouldn't be an issue. Just wrap the module in some parent elements. The problem, of course, is this is breaking conventions from both the new template and the CMS flow...

The third solution is the best in the long run but I would hold off on this since it would require more planning than meets the eye. I think this might be a viable option for a general-based template and not for this.

So maybe we try option 2?

**Comment by johnsiwicki** [comment]
I added some css as a starting point https://www.suredrybasements.com/about-us/photo-gallery/24234-album-crawlspace-waterproofing-in-baileys-harbor-wi.html?cache=0&dev_template=1&dev_content=1#ad-image-0

**Comment by johnsiwicki** [comment]
@ronaldjosephjones we fixed all the issues on our widgets right
