### ISSUE TITLE
Increase Space Around Links

### ISSUE THREAD

**Issue by johnsiwicki** [bs-production/sure-dry-template#20]
<img width="373" alt="Screen Shot 2021-09-27 at 7 58 30 AM" src="https://user-images.githubusercontent.com/1509641/134903722-5989cb6e-fca8-4309-a5f3-871fafc416f4.png">

**Comment by IamStephan** [comment]
Commit: d10684a
![image](https://user-images.githubusercontent.com/36214317/135111496-806f5af4-51d1-4819-bb26-6acaaed9098d.png)

**Comment by IamStephan** [comment]
The home page has an extra margin on the left for the list. I added padding so it would work on all pages but now the list on the homepage has extra padding and is pushed too far to the right
