### ISSUE TITLE
Before and after slider/carousel has some functionality issues 

### ISSUE THREAD

**Issue by IamStephan** [bs-production/sure-dry-template#4]
This just seems to happen on one page, but I'm not sure if this is supposed to be a slider/carousel. It looks like it should be one but it does not behave that way

The page: [Basement Crack Repairs](https://www.suredrybasements.com/basement-waterproofing/basement-crack-repair.html)

**Comment by johnsiwicki** [comment]
I changed the widget template on this one to be more compatiable
