### ISSUE TITLE
Photo gallery sub pages components

### ISSUE THREAD

**Issue by IamStephan** [bs-production/sure-dry-template#5]
[Example page](https://www.suredrybasements.com/basement-waterproofing/photo-gallery/24234-album-crawlspace-waterproofing-in-baileys-harbor-wi.html)

The carousel and thumbnails at the bottom are not working (Both functionally and styles). I'm not sure if this is a module template issue or something that needs to be done on the template side (Custom scripts and styles).

**Comment by johnsiwicki** [comment]
We have a Global fix waiting to roll out. We might need a temp fix in the meantime
