### ISSUE TITLE
The BBB cred logo is floating inside a float and looks bad on mobile

### ISSUE THREAD

**Issue by IamStephan** [bs-production/sure-dry-template#6]
[The page](https://www.suredrybasements.com/foundation-repair-wisconsin/about-foundation-supportworks.html).

The BBB logo inside the second right float is floating to the left. This float inside float is making the logo stretch full width on mobile. Maybe find another way to place the logo or just add another class to it that is not float-related.

**Comment by ronaldjosephjones** [comment]
Hi Stephan,
I removed the floats from that BBB logo and wrapped it and its paragraph in a flexbox wrapper. Looks better now: https://www.suredrybasements.com/foundation-repair-wisconsin/about-foundation-supportworks.html?cache=0&dev_content=1
