### ISSUE TITLE
Missing inline before and after widget

### ISSUE THREAD

**Issue by IamStephan** [bs-production/sure-dry-template#7]
Pages:
- [x] https://www.suredrybasements.com/concrete-repair/concrete-driveway-repair.html
- [x] https://www.suredrybasements.com/concrete-repair/sidewalk-repair.html
- [x] https://www.suredrybasements.com/concrete-repair/pool-deck-repair.html

**Comment by johnsiwicki** [comment]
I added the jquery plugin that those pages use to each page
