### ISSUE TITLE
Style conflicts with module and template (social share icons)

### ISSUE THREAD

**Issue by IamStephan** [bs-production/sure-dry-template#9]
[The page](https://www.suredrybasements.com/about-us/customer-reviews/33286-54956-wi.html)

I'm not entirely sure where the conflict is coming from but something is causing the icons to be pushed from the center.

**Comment by johnsiwicki** [comment]
If you add the blow to that rule you should get the icon centered

```
.review_details .review_details_body .review-icons .social-share-inline a:before {
    transform: unset;
    top: 0;
    left: 0;
}
}
```
